ALTER TABLE `Products` ADD COLUMN `DISCOUNT_PERCENT` int DEFAULT 0;
ALTER TABLE `Products` ADD COLUMN `SALES_COUNT` int DEFAULT 0;
ALTER TABLE `Products` ADD COLUMN `LOCATION` varchar(100) DEFAULT 'Ho Chi Minh';
ALTER TABLE `Products` ADD COLUMN `BRAND` varchar(100) DEFAULT 'Originals';
ALTER TABLE `Products` ADD COLUMN `RATING` int DEFAULT 5;
ALTER TABLE `Products` ADD COLUMN `IS_MALL` boolean DEFAULT FALSE;
ALTER TABLE `Products` ADD COLUMN `IS_FAVORED` boolean DEFAULT FALSE;
