-- V8: Chuyển đổi bảng Products sang utf8mb4 và bổ sung tồn kho, phân loại, trạng thái và bộ đếm nhận xét
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE Products CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE Products
ADD COLUMN STOCK_QUANTITY INT DEFAULT 100,
ADD COLUMN CATEGORY VARCHAR(100) DEFAULT 'Giày Sneaker',
ADD COLUMN STATUS VARCHAR(20) DEFAULT 'ACTIVE',
ADD COLUMN REVIEW_COUNT INT DEFAULT 0,
ADD COLUMN UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
MODIFY COLUMN RATING DOUBLE DEFAULT 5.0;

-- Tạo bảng Chi tiết Đánh giá Sản phẩm (Product_Reviews)
CREATE TABLE IF NOT EXISTS Product_Reviews (
    Review_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Product_Code VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    Username VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    Rating_Value INT NOT NULL,
    Comment TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    Image_Url VARCHAR(255),
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_product FOREIGN KEY (Product_Code) REFERENCES Products(CODE) ON DELETE CASCADE
);

SET FOREIGN_KEY_CHECKS = 1;
