-- Flyway Migration V9: Upgrade Accounts Table with OAuth2 Provider ID, Full Name, Avatar URL, Timestamps & Security fields

ALTER TABLE Accounts 
    ADD COLUMN FULL_NAME VARCHAR(100) NULL AFTER USER_NAME,
    ADD COLUMN PHONE_NUMBER VARCHAR(20) NULL AFTER EMAIL,
    ADD COLUMN AVATAR_URL VARCHAR(255) NULL AFTER PHONE_NUMBER,
    ADD COLUMN ACCOUNT_NON_LOCKED BOOLEAN DEFAULT TRUE AFTER ACTIVE,
    ADD COLUMN FAILED_ATTEMPTS INT DEFAULT 0 AFTER ACCOUNT_NON_LOCKED,
    ADD COLUMN PROVIDER_ID VARCHAR(255) NULL AFTER PROVIDER,
    ADD COLUMN CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP AFTER PROVIDER_ID,
    ADD COLUMN UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER CREATED_AT,
    ADD COLUMN LAST_LOGIN DATETIME NULL AFTER UPDATED_AT;

-- Fill FULL_NAME for existing accounts
UPDATE Accounts SET FULL_NAME = USER_NAME WHERE FULL_NAME IS NULL OR FULL_NAME = '';
